CREATE TABLE Authors (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Author_Name VARCHAR (30)
);

CREATE TABLE Customers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Customer_Name VARCHAR (30) NOT NULL,
    Customer_Email VARCHAR (30) NOT NULL UNIQUE
);

CREATE TABLE Books (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Book_Name VARCHAR (30) NOT NULL,
    Authors_Id INTEGER NULL,
    FOREIGN KEY (Authors_Id) REFERENCES Authors (ID)
);

CREATE TABLE Rents (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Books_Id INTEGER,
    Customers_Id INTEGER,
    State VARCHAR (25),
    FOREIGN KEY (Books_Id) REFERENCES Books (ID),
    FOREIGN KEY (Customers_Id) REFERENCES Customers (ID)
);