CREATE TABLE Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Full_Name VARCHAR (25) NOT NULL,
    Buyer_Email VARCHAR (25) NOT NULL UNIQUE,
    Registration_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR (25) NOT NULL,
    Price FLOAT NOT NULL DEFAULT 0,
    Entry_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Brand VARCHAR (25) NOT NULL,
    Stock_Available SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE Payment_Methods (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Method_Type VARCHAR (25) NOT NULL DEFAULT 'Cash',
    Bank_Name VARCHAR (25) NULL DEFAULT 'N/A'
);

CREATE TABLE Invoices (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    User_Id INTEGER REFERENCES Users (Id),
    Purchase_Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Total_Amount FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE Reviews (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Products_Id INTEGER REFERENCES Products (Id),
    Users_Id INTEGER REFERENCES Users (Id),
    Comment TEXT NOT NULL,
    Rating TINYINT NOT NULL DEFAULT 1,
    Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Shopping_Cart (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    User_Id INTEGER REFERENCES Users (Id)
);

CREATE TABLE Cart_Items (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Shopping_Cart_Id INTEGER REFERENCES Shopping_Cart (Id),
    Products_Id INTEGER REFERENCES Products (Id),
    Quantity SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE Invoice_Payment (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Invoice_Id INTEGER REFERENCES Invoices (Id),
    Payment_Method_Id INTEGER REFERENCES Payment_Methods (Id),
    Amount_Paid FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE Products_Per_Invoice (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Invoice_Id INTEGER REFERENCES Invoices (Id),
    Products_Id INTEGER REFERENCES Products (Id),
    Quantity SMALLINT NOT NULL DEFAULT 0,
    Total_Amount FLOAT NOT NULL DEFAULT 0
);